CoursePlatform/CoursePlatform/urls.py
from django.contrib import admin
from django.urls import include, path
from accounts import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('', include("accounts.urls")),
    path('', include("course.urls")),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CoursePlatform/course/urls.py
from django.conf import settings
from django.conf.urls.static import static
from course.views import CourseList, CourseDetailView, EnrollStudent, CoursePlay
from django.urls import path
from django.conf import settings

urlpatterns = [
    path('course/', CourseList.as_view()),
    path('course/<slug:slug>/', CourseDetailView.as_view(), name='course-detail'),
    path('enroll/<slug:slug>/', EnrollStudent.as_view()),
    path('course/<slug:slug>/play/', CoursePlay.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CoursePlatform/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Profile
from functools import partial

DateInput = partial(forms.DateInput, {'class': 'datepicker'})


class FullUserCreationForm(UserCreationForm):
    """
    Extends standard usercreationform by including email address
    """
    CHOICES = (('1', "Register as a Student",), ('2', "Register as a Partner",))
    email = forms.EmailField(required=True)
    user_type = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)

    class Meta:
        model = User
        fields = ["user_type", "username", "email", "password1", "password2"]
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'placeholder': 'E-Mail'}),
        }


class UserUpdateForm(forms.ModelForm):
    """
    A form for updating common fields for all types of users: email, username
    """

    class Meta:
        model = User
        fields = ["username", "email"]


class ProfileUpdateForm(forms.ModelForm):
    """
    A form for updating student's profile details
    """
    profile_pic = forms.ImageField(label='Profile picture', required=False,
                                   error_messages={'invalid': "Image files only"}, widget=forms.FileInput)
    birth_date = forms.DateField()

    class Meta:
        model = Profile
        fields = ['profile_pic', 'first_name', 'last_name', 'gender', 'birth_date', 'country']
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name'})
        }

CoursePlatform/templates/base_frontend.html
{% load static %}
<!DOCTYPE html>
<html lang="en-us">

<head>

    <title>Etrain</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" id="favicon" href="{% static '/images/favicon.ico' %}"/>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&display=swap" rel="stylesheet">

    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static '/css/owl.carousel.css' %}">


    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static '/css/owl.theme.css' %}">


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.6/jquery.fancybox.min.css">


    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
          integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static '/css/media.css' %}">
    <link rel="stylesheet" href="{% static '/css/toast-plugin.css' %}">


    <!-- style CSS -->
    <link rel="stylesheet" href="{% static '/css/style.css' %}">

</head>

<body>
<div class="wrapper">

    <header class="main-header">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
                <a class="navbar-brand" href="/"><img src="{% static '/images/logo.png' %}" width="140px" alt=""></a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">


                        <li class="nav-item menu-primary"><a href="/">Home</a></li>
                        <!-- <li><a href="#">About Us</a></li> -->
                        <li class="nav-item menu-primary"><a href="/course">Courses</a></li>
                        <!-- <li><a href="/contact">Contact Us</a></li> -->


                    </ul>
                    <ul class="navbar-nav ml-lg-auto">
                        <li class="nav-item badge hdr-login text-right text-lg-center py-3 py-lg-0 px-4 px-lg-0 mr-3 mr-lg-2">
                            {% if user.is_authenticated %}
                            <a title="Profile" href="/profile/"><i class="far fa-user"></i> {{request.user.username|title}}</a>
                            {% else %}
                            <a href="/login/"><i class="far fa-user"></i>Login</a>
                            {% endif %}
                        </li>
                        <li class="nav-item badge hdr-login text-right text-lg-center py-3 py-lg-0 px-4 px-lg-0 mr-3 mr-lg-0">
                            {% if user.is_authenticated %}
                            <a title="Logout" href="/logout/"><i class="fas fa-sign-out-alt"></i></a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>


    {% block content %}

    {% endblock %}
    <!-- footer part start-->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-3 col-sm-6">
                    <div class="footer-widget">
                        <img src="{% static '/images/logo.png' %}" class="ftr-logo" alt="">
                    </div>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <div class="footer-widget">
                        <h6>Contact Address</h6>
                        <ul class="contact-info">
                            <li>Aeschstrasse 10, 8834 Schindellegi</li>
                            <li><a href="#">info@itrainplatform.com</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <div class="footer-widget">
                        <h6>Popular Courses</h6>
                        <ul>
                            <!-- <li><a href="courses-details.html">Blockchain course(20)</a></li>
                            <li><a href="courses-details.html">Sustainable Investment(23)</a></li>
                            <li><a href="courses-details.html">Impact Investing(15)</a></li>
                            <li><a href="courses-details.html">Javascript(20)</a></li>
                            <li><a href="courses-details.html">Web Development(20)</a></li>
                            <li><a href="courses-details.html">System Design(14)</a></li>
                            <li><a href="courses-details.html">Science Fiction(13)</a></li> -->
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <div class="footer-widget">
                        <h6>Subscribe</h6>
                        <p>Stay updates with our latest trends.</p>

                        <form action="" class="subscribe-form">
                            <input type="text" placeholder="Email Address" class="form-control">
                            <input type="submit" value="search ">

                        </form>
                    </div>
                </div>
                <div class="col-md-12 mt-5">
                    <div class="footer-widget">
                        <p class="copyright text-center">All Rights Reserved ©2020. Etrain
                        </p>
                        <div class="bottom-anchors mt-4 text-center">
                            <ul class="d-flex justify-content-center">
                                <li class="mx-2"><a href="">Cookie Policy</a></li>
                                <li class="mx-2"><a href="">Privacy Policy</a></li>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static '/js/jquery.js' %}"></script>
    <!-- popper js -->


    <!-- bootstrap js -->
    <script src="{% static '/js/bootstrap.min.js' %}"></script>

    <script src="{% static '/js/owl.carousel.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.6/jquery.fancybox.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static '/js/custom.js' %}"></script>
    <script src="{% static '/js/toast-plugin.js' %}"></script>
    <script>
    $(function() {
        $("#id_birth_date").datepicker({maxDate: "-1D"});
    });



    </script>
    <script>

      $('#id_username ,#id_password,#id_username , #id_email,#id_password1,#id_password2').addClass('form-control');
      $('#id_email').attr('placeholder', 'Email');
      $('#id_password').attr('placeholder', 'Password');
      $('#id_password1').attr('placeholder', 'Password');
      $('#id_password2').attr('placeholder', 'Confirm Password');

      $('#id_username').attr('placeholder', 'Username');



    </script>

    {% if messages %}
    {% for message in messages %}
    {% if message.tags == 'success'%}
    <script type=text/javascript>
         var  message= '{{ message }}';
          $.toast({
                      heading: 'Success',
                      text: message,
                      icon: 'success',
                      loader: true,        // Change it to false to disable loader
                      loaderBg: '#4064AD',  // To change the background
                      position:'top-right'
                  })












    </script>
    {% elif message.tags == 'error'%}

    <script type=text/javascript>
      var  message= '{{ message }}';
       $.toast({
                   heading: 'Error',
                   text: message,
                   icon: 'error',
                   loader: true,        // Change it to false to disable loader
                   loaderBg: '#4064AD',  // To change the background
                   position:'top-right'
               })












    </script>

    {% endif %}
    {% endfor %}
    {% endif %}
</div>
</body>

</html>